// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAH5m7s6syt03uTHidRthfBs-9kFVlWVrg',
    appId: '1:415645183375:web:31cdb526157d93541a6ffa',
    messagingSenderId: '415645183375',
    projectId: 'flutterclass-1380b',
    authDomain: 'flutterclass-1380b.firebaseapp.com',
    storageBucket: 'flutterclass-1380b.appspot.com',
    measurementId: 'G-W48X1XECJ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5P2aSwCcSEvEnqOnrVZC_nPrU-9dpkcc',
    appId: '1:415645183375:android:1df208260900ee0a1a6ffa',
    messagingSenderId: '415645183375',
    projectId: 'flutterclass-1380b',
    storageBucket: 'flutterclass-1380b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNQPLcSw1RQtEmR1jruvDmGWfJ0kH-qLk',
    appId: '1:415645183375:ios:f40405fba5c53abb1a6ffa',
    messagingSenderId: '415645183375',
    projectId: 'flutterclass-1380b',
    storageBucket: 'flutterclass-1380b.appspot.com',
    iosBundleId: 'com.example.firstapplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNQPLcSw1RQtEmR1jruvDmGWfJ0kH-qLk',
    appId: '1:415645183375:ios:f40405fba5c53abb1a6ffa',
    messagingSenderId: '415645183375',
    projectId: 'flutterclass-1380b',
    storageBucket: 'flutterclass-1380b.appspot.com',
    iosBundleId: 'com.example.firstapplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAH5m7s6syt03uTHidRthfBs-9kFVlWVrg',
    appId: '1:415645183375:web:eb0824541ad2e26a1a6ffa',
    messagingSenderId: '415645183375',
    projectId: 'flutterclass-1380b',
    authDomain: 'flutterclass-1380b.firebaseapp.com',
    storageBucket: 'flutterclass-1380b.appspot.com',
    measurementId: 'G-CHDXG2MM81',
  );
}
